added relaxed attention to encoder-decoder attention (arxiv.org/abs/2107.01275)
freewym/espresso pull request #71
Opened 2021-11-30 15:03 UTC by timolohrenz

Hey, thanks for the nice work on the espresso toolkit.

Our method 'relaxed attention' was developed using espresso and we want to contribute this here for others to explore. The corresponding paper can be found here ([https://arxiv.org/abs/2107.01275](https://arxiv.org/abs/2107.01275)) and was accepted for presentation at ASRU. 

Without adding any additional parameters or interference complexity we achieved significant WER reduction on WSJ. It seems the works especially good for small datasets. On single-training tests with the most recent version we achieved a eval92 WER of 3.76% compared to 4.16% with the standard recipe. In the paper we also validated with multiple seeds.  

I am looking forward to your comments on that feature.

Best regards from germany,
   Timo Lohrenz

2021-11-30 23:23 UTC, freewym requested changes
Hi Timo, thanks for your contribution! I have several small comments below:

2021-11-30 23:23 UTC, freewym commented on examples/asr_wsj/run.sh
> +    --criterion label_smoothed_cross_entropy_v2 --relaxed-attention 0.35 --label-smoothing 0.05 --smoothing-type temporal \
Move this option to the if block at line 284. The code only applies to transformers in this PR, right?

2021-11-30 23:23 UTC, freewym commented on espresso/models/transformer/speech_transformer_config.py
> +    relaxed_attention: float = field(
perhaps rename it to `relaxed_attention_weight`?

2021-11-30 23:23 UTC, freewym commented on fairseq/modules/multihead_attention.py
> +        encoder_attn_relaxation: float = None,
not necessay as it has already been specified in the constructor

2021-11-30 23:23 UTC, freewym commented on fairseq/modules/transformer_layer.py
> +        encoder_attn_relaxation: float = None,
remove this line with the same reason above

2021-11-30 23:23 UTC, freewym commented on fairseq/modules/transformer_layer.py
> +                encoder_attn_relaxation=encoder_attn_relaxation,
remove this line with the same reason above

2021-11-30 23:23 UTC, freewym commented on fairseq/modules/multihead_attention.py
> +            attn_weights = attn_weights \
you can simply do
```python
attn_weights = (1.0 - self.relaxed_attention_weight) * attn_weights + self.relaxed_attention_weight / src_len
```

Actually I have a question here: the lengths of the encoder output vary across different examples in a batch. Would it be better to take that into account when doing smoothing with a uniform distribution, i.e., `src_len` can be different for different examples in a batch?

2021-11-30 23:23 UTC, freewym commented on fairseq/modules/multihead_attention.py
> +        if self.training and self.relaxed_attention_weight is not None:
-> `if self.training and self.relaxed_attention_weight > 0.0:`

2021-12-01 13:51 UTC, timolohrenz commented on fairseq/modules/multihead_attention.py
> +            attn_weights = attn_weights \
Yes, good question indeed! We actually tried out both but due to space limitations did not include these experiments into the paper. 

It is possible to use the key_padding_mask to get the exact src_len values for each utterance in the batch. This makes the implementation slightly more bulky and we observed that the WER results (averaged over five trainings with five different seeds) are slightly higher:

No relaxed attention:                                  6.69 dev93 / 4.45 eval92
Relaxed attention (this implementation):    5.76 dev93 / 3.52 eval92
Relaxed attention (exact src_lens):              5.78 dev93 / 3.84 eval92

We assume that the amount of "randomization" due to the different batch lengths is enough to put stress on the attention during training without creating a training/test mismatch.

2021-12-01 13:55 UTC, timolohrenz commented on examples/asr_wsj/run.sh
> +    --criterion label_smoothed_cross_entropy_v2 --relaxed-attention 0.35 --label-smoothing 0.05 --smoothing-type temporal \
Yes thats true. I will do that. We also observed improvements with the LSTM model but with slightly smaller relaxation weights. For Librispeech it also works but it still requires more tuning. Its likely that I will add those values in a future PR.

2021-12-01 15:02 UTC, timolohrenz commented
Hey Yiming, thanks for your quick response. I updated everything according to your comments. You can find more detailed responses above. Let me know if there are any concerns /issues left.

2021-12-01 22:23 UTC, freewym commented on fairseq/modules/transformer_layer.py
> +            relaxed_attention_weight=cfg.decoder.relaxed_attention_weight,
I believe the reason of the check failure is that the option is added in Espresso's transformer config, but here at this line it is using fairseq's config. Also generally I prefer not to touch the fairseq code if possible. So could please override `build_encoder_attention()` in the class `espresso.modules.transformer_with_relative_positional_embedding_layer.TransformerWithRelativePositionalEmbeddingDecoderLayerBase`?

2021-12-02 16:04 UTC, timolohrenz commented on fairseq/modules/transformer_layer.py
> +            relaxed_attention_weight=cfg.decoder.relaxed_attention_weight,
Okay, that's easily possible. Are changes to fairseq's multiheadattention.py okay then? Cause thats where our method is applied. I could also try to add a `espresso.module.MultiheadAttentionWithRelaxation` class as a child of `fairseq.modules.MultiheadAttention` and overwrite the `forward() `function with our code, but that would reuse about 90% of the fairseq code. What's your recommandation for best practice?

2021-12-02 20:57 UTC, freewym commented on fairseq/modules/transformer_layer.py
> +            relaxed_attention_weight=cfg.decoder.relaxed_attention_weight,
Not for MultiheadAttention, as like what you said it will duplicate most of the code from MultiheadAttention. Only do it for the Transformer layer.

2021-12-03 01:41 UTC, merged

2021-12-03 01:42 UTC, freewym commented
Thanks, merging. The check failure is due to format issues. I will fix them myself

2021-12-03 10:20 UTC, timolohrenz commented
Thanks Yiming. I need to get the checks running locally in the future so that I can take care of that myself. There will be more PRs in the future as we continue to look into relaxed attention and do a lot of other research using the espresso toolkit.

2021-12-03 22:54 UTC, freewym commented
You can refer to https://www.freecodecamp.org/news/auto-format-your-python-code-with-black/ for reformatting